### ISSUE TITLE
Virtual Server type option 

### ISSUE THREAD

**Issue by VAdamec** [DealerDotCom/terraform-provider-bigip#11]
Standard should be default (now Performance (layer 4)), rest as an option (stateless, dhcp, ...)

**Comment by VAdamec** [comment]
https://devcentral.f5.com/questions/wrong-virtualserver-type

**Comment by aburnett** [comment]
It defaults to what the API supplies for now. Are you suggesting the provider should provide defaults to match the GUI? That thread you linked to seems to just explain how the defaults differ between API and GUI?

**Comment by aburnett** [comment]
To clarify a bit, there is no "type" property on the Virtual Server object. The GUI seems to provide that as a wrapper that sets a pre-canned set of profiles and other settings. So, to that end I don't think we should provide a "type" parameter to match the GUI because they we will forever be coupled to whatever logic is tied to that drop down (would could easily change).

We should maintain parity with the iControlREST API, not the management GUI.

**Comment by VAdamec** [comment]
Yeap I saw that there is nothign like that in /mgmt/tm/ltm/virtual or policies, but we need to find some way, without this you cannot set SSL (#9 ssl enhancement) as this is part of type standard + protocol TCP. I'll dig through F5 documentation if there is any option.

**Comment by aburnett** [comment]
If you have an existing SSL certificate uploaded you can set SSL on the virtual server by specifying the name of a client-ssl profile in the profiles list like so:

```
resource "bigip_ltm_virtual_server" "https" {
  name = "my-vs-name"
  destination = "${var.vip_ip}"
  port = 443
  pool = "${var.pool}"
  profiles = ["tcp","my-awesome-ssl-cert","http"]
  source_address_translation = "automap"
}
```

You can see the certs available via the iControlREST at `/mgmt/tm/ltm/profile/client-ssl`

**Comment by VAdamec** [comment]
Ahh ok, so just add "profiles" option to documentation :-)
